### PR TITLE
Feature/recommended services

### PR DESCRIPTION
**Pull request by appsol**
### Summary
https://trello.com/c/kBP9HlxC

- Add a 'score' field to Services with a default of 0.
- Limit scores to between 1 and 5.
- Add field_value_factor function to ElasticSearch to allow score value to influence search results
- Update Search History to use the existing query path and the updated query path

### Development checklist
- [x] Changes have been made to the API?
  - [x] If so, the OpenAPI specification has been updated
- [x] Database migrations have been added?
  - [x] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
NA

### CODE REVIEW

**Comment by appsol** [comment]
@matthew-inamdar This and the #43 PR are not completing their builds in CI. This is due to an error in composer install. I have tried to replicate the error locally, but cannot. Can you have a look at the CI builds and see if you can see what is causing the error?

**Comment by matthew-inamdar** [comment]
@appsol could you resolve these conflicts please 🙂

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
Code all looks good. Failing tests just need addressing.

**Review by matthew-inamdar — APPROVED** [review]
LGTM 👍

**Pull request merged**
