### PR TITLE
Feature/make organisation description optional

### PR DESCRIPTION
**Pull request by appsol**
### Summary
https://trello.com/c/UJEeyBcH

- Database migration, change organisations/description to nullable
- Update tests to allow organisations to be created, updated and imported without a description
- Update request validation to allow null description
- Update docs to reflect optional description

### Development checklist
- [x] Changes have been made to the API?
  - [x] If so, the OpenAPI specification has been updated
- [x] Database migrations have been added?
  - [x] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
NA

### CODE REVIEW

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
There seems to be a lot of unrelated changes in this PR?

**Comment by appsol** [comment]
@matthew-inamdar 
- Resolved the merge conflicts with ERD.mwb.
- Merged in develop

Unfortunately develop is getting a bit out of date with the backlog of PR merges. This means I sometimes have to pull other feature branches into a current feature branch to avoid having to work with code that I know is going to conflict with changes I have made.

The changed files relating to this branch are:
- app/Docs/Schemas/Organisation/UpdateOrganisationSchema.php
- app/Http/Controllers/Core/V1/Organisation/ImportController.php
- app/Http/Controllers/Core/V1/OrganisationController.php
- app/Http/Requests/Organisation/StoreRequest.php
- app/Http/Requests/Organisation/UpdateRequest.php
- database/factories/OrganisationFactory.php
- database/migrations/2020_10_12_161007_update_organisations_make_description_nullable.php
- tests/Unit/Models/OrganisationTest.php
- tests/Feature/OrganisationsTest.php
- database/diagrams/ERD.mwb

**Comment by matthew-inamdar** [comment]
@appsol can you checkout the non-related files from `develop` and commit them to this branch in that case?

**Comment by appsol** [comment]
@matthew-inamdar Already merged in develop here https://github.com/Healthy-London-Partnership/api/pull/36/commits/eeff206cf1d67afcb8ccb10e2180e915f7c9e826

**Comment by matthew-inamdar** [comment]
> @matthew-inamdar Already merged in develop here [eeff206](https://github.com/Healthy-London-Partnership/api/commit/eeff206cf1d67afcb8ccb10e2180e915f7c9e826)

There are 20 changed files in this PR, but you've said only 10 files are relating to this PR. Should we not remove the unrelated files from this PR in that case?

**Comment by appsol** [comment]
@matthew-inamdar I've removed as many of the changes as possible in this PR, but it is now so out of sync with develop that it's getting hard to keep it contained. I suggest we try to get this into develop and move on.

**Comment by matthew-inamdar** [comment]
@appsol could you take a look at these conflicts please 🙂

**Comment by appsol** [comment]
- Conflicts resolved

There is some legacy code in here that will conflict with the Copy across Loop permissions. I would merge this first then the Loop permissions PR.

**Comment by matthew-inamdar** [comment]
Sorry @appsol it looks like there's another conflict

**Comment by appsol** [comment]
@matthew-inamdar resolved conflicts

**Review by matthew-inamdar — APPROVED** [review]
LGTM 👍

**Pull request merged**
