### PR TITLE
Feature/organisation duplicate management

### PR DESCRIPTION
**Pull request by appsol**
### Summary
https://trello.com/c/Dd3mNnqp

- Check for duplicates within transaction. If duplicates found transaction is aborted with exception
- Duplicates are checked using a GROUP BY clause.
- Names are normalised to a limited character set as the sheet is imported so the comparison is more reliable
- Names within the tables are then normalised during the duplicate search query to only alphanum characters
- Duplicate clashes can be ignored by passing the ID of clashing existing organisations
- If some organisations are flagged to ignore clashes, but other clashes exist, then the whole insert is aborted (atomic)
- Duplicates are returned along with the spreadsheet row data that clashed with them.

### Development checklist
- [x] Changes have been made to the API?
  - [x] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
NA

### CODE REVIEW

**Comment by appsol** [comment]
@matthew-inamdar Leave this until I get the merge conflicts resolved.

**Comment by appsol** [comment]
@matthew-inamdar Ready for review

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
I've noticed `SpreadsheetController` is in here?

Could you please take a look over it and tidy it up before review?

**Comment by appsol** [comment]
Done.

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
Looking good 👍 

The import fails when the XLS file has duplicates within itself. 

The API seems to treat these as already existing organisations in the DB (as it looks like they are, from a previous insert in the transaction).

If it's going to add a lot more work or require changes to the design, then let's let @AyupMike know.

**Comment by appsol** [comment]
@matthew-inamdar In my testing, I have created an import which contains both a duplicate of an existing row as well as a duplicate of a row within the import. The import fails with 422 and returns the duplicate import rows as a duplication error, which should be the desired behaviour shouldn't it? If a user has accidentally included an organisation twice in the spreadsheet, we should flag that rather than allow organisations to be imported which will need to be cleaned out later.

**Comment by matthew-inamdar** [comment]
@appsol I agree, we should definitely flag it. 

Am I right in thinking the option to ignore duplicates on the admin web app doesn't have any effect when the duplicates are within the same spreadsheet the user is trying to upload?

**Comment by appsol** [comment]
@matthew-inamdar Yes, the ignore duplicates is ID based so does not work with duplicates within the spreadsheet. However duplicates in the spreadsheet will get flagged as duplicates. I think we need a different sort of notification for these as they cannot be 'ignored' in the same way as existing duplicates.

**Comment by appsol** [comment]
@matthew-inamdar Resolved a couple of edge cases around duplicate rows in the spreadsheet, plus a bug where duplicate rows already in the database where being returned as possible duplicates.

**Review by matthew-inamdar — APPROVED** [review]

**Pull request merged**
