### PR TITLE
Added test around VideoEmbed rule. Changed rule to pass

### PR DESCRIPTION
**Pull request by appsol**
Ref: Trello - Vimeo links not supported when adding a video to a service (https://trello.com/c/PwbyHbZI)

### CODE REVIEW

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
Looks good 👍 

Could we remove the files from the PR which have had permission changes as well as `package-lock.json`?

Could we also use camel case for PHP variable names?

Edit: Also, will removing `player.vimeo.com` cause any issues? I'm not sure if that should still be a valid domain for existing videos?

**Comment by appsol** [comment]
I've added back in player.vimeo.com, also switched to camelCase for variables.
I've switched git config core.fileMode false so any filemode changes should not come through in future, but I can't see a simple solution to removing these from the commit. Tried reset -- Head~1 [file] but it's not getting it, so might be easier just to ignore for this time.

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
@appsol You can checkout the files from the `develop` branch and then push another commit:

```bash
git checkout develop -- package-lock.json storage/**
```

It seems your test needs updating to include the original domain too.

**Comment by appsol** [comment]
Apologies. Rushing to try and make up time and missing things. I've checked out the chmod files from develop and fixed the test. All tests passing now.

**Review by matthew-inamdar — APPROVED** [review]
LGTM 👍

**Pull request merged**
